[package]
name = "zork-ui-egui"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
zork-core = { path = "../zork-core" }
eframe = { version = "0.27", features = ["wgpu"] }
egui_extras = "0.27"
egui = "0.27"
image = { version = "0.24", default-features = false, features = ["png", "jpeg", "webp"] }
webp-animation = "0.8"
ffmpeg-next = { version = "6", optional = true, default-features = false, features = ["codec", "format", "software-scaling"] }
pollster = "0.3"
rodio = { version = "0.17", default-features = true }
serde_json = { workspace = true }
cpal = { version = "0.15", optional = true }
whisper-rs = { version = "0.11", optional = true, default-features = false }
chrono = "0.4"

[features]
mp4-video = ["ffmpeg-next"]
speech_input = ["cpal", "whisper-rs"]
speech_input_cuda = ["speech_input", "whisper-rs/cuda"]

[[bin]]
name = "zork-ui-egui"
path = "src/main.rs"
